Import libraries

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import self
plt.style.use('ggplot')

Reading CSV and creation dataframe

In [25]:
df_actors = pd.read_csv('C:\\Users\\Windows11\\Desktop\\dataset\\actors.csv')

Checking CSV dimension

In [26]:
df_actors.shape

(5798450, 3)

Showing CSV line

In [27]:
df_actors.head(5)

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

Showing CSV index

In [28]:
df_actors.columns

Index(['id', 'name', 'role'], dtype='object')

Showing CSV columns types

In [29]:
df_actors.dtypes

id       int64
name    object
role    object
dtype: object

Obtaining a statistical summary of the numerical columns of the CSV DataFrame

In [30]:
df_actors.describe()

                 id
count  5.798450e+06
mean   1.302557e+06
std    2.551917e+05
min    1.000001e+06
25%    1.079557e+06
50%    1.236225e+06
75%    1.483358e+06
max    1.941597e+06

Show the first few rows of the dataframe

In [31]:
df_actors.head()

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

Identify missing values or null values

In [32]:
df_actors.isna()

            id   name   role
0        False  False  False
1        False  False  False
2        False  False  False
3        False  False  False
4        False  False  False
...        ...    ...    ...
5798445  False  False  False
5798446  False  False  False
5798447  False  False  False
5798448  False  False   True
5798449  False  False   True

[5798450 rows x 3 columns]

Showing the sum of the number of null values per columns

In [33]:
df_actors.isna().sum()

id            0
name          4
role    1361559
dtype: int64

Showing if any of our data is duplicated

In [34]:
df_actors.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
5798445    False
5798446    False
5798447    False
5798448    False
5798449    False
Length: 5798450, dtype: bool

Returns a new DataFrame containing only the rows that are duplicated

In [37]:
df_actors.loc[df_actors.duplicated(subset = 'id')]

              id               name                 role
1        1000001       Ryan Gosling                  Ken
2        1000001    America Ferrera               Gloria
3        1000001  Ariana Greenblatt                Sasha
4        1000001           Issa Rae               Barbie
5        1000001      Kate McKinnon               Barbie
...          ...                ...                  ...
5798444  1941596     Sandrine Pinna                  NaN
5798445  1941596            Marc Ma            Ba Cai/巴莱
5798446  1941596                线雨轩              Tata/塔塔
5798447  1941596       Jiang Yixuan  Zuo Yila（Zoila）/佐伊拉
5798449  1941597      Keiko Oginome                  NaN

[5164148 rows x 3 columns]

In [39]:
df_actors.loc[df_actors.duplicated(subset='name')]

              id            name                 role
327      1000005    Ryan Gosling            Sebastian
604      1000007   Casey Affleck           Tom Cooper
613      1000007      Matt Damon                 Mann
623      1000007    Jeff Hephner               Doctor
628      1000007     Flora Nolan        Girl on Truck
...          ...             ...                  ...
5798444  1941596  Sandrine Pinna                  NaN
5798445  1941596         Marc Ma            Ba Cai/巴莱
5798447  1941596    Jiang Yixuan  Zuo Yila（Zoila）/佐伊拉
5798448  1941597  Hiroshi Mikami                  NaN
5798449  1941597   Keiko Oginome                  NaN

[4197787 rows x 3 columns]

In [40]:
df_actors.loc[df_actors.duplicated(subset='role')]

              id             name    role
4        1000001         Issa Rae  Barbie
5        1000001    Kate McKinnon  Barbie
6        1000001  Alexandra Shipp  Barbie
7        1000001      Emma Mackey  Barbie
8        1000001         Hari Nef  Barbie
...          ...              ...     ...
5798439  1941563         Lan Xiya     NaN
5798440  1941563             黄子弘凡     NaN
5798444  1941596   Sandrine Pinna     NaN
5798448  1941597   Hiroshi Mikami     NaN
5798449  1941597    Keiko Oginome     NaN

[3878364 rows x 3 columns]

Query on columns

In [59]:
df_actors.query('id == 1020695')

             id               name                     role
584993  1020695      Burt Reynolds          Lt. Phil Gaines
584994  1020695  Catherine Deneuve           Nicole Britton
584995  1020695        Ben Johnson          Marty Hollinger
584996  1020695      Paul Winfield           Louis Belgrave
584997  1020695     Eileen Brennan          Paula Hollinger
584998  1020695       Eddie Albert              Leo Sellers
584999  1020695    Ernest Borgnine                  Santuro
585000  1020695     Catherine Bach            Peggy Summers
585001  1020695        Jack Carter            Herbie Dalitz
585002  1020695      James Hampton               Bus Driver
585003  1020695    Colleen Brennan         Gloria Hollinger
585004  1020695      Chuck Hayward         Morgue Attendant
585005  1020695     David Estridge                   Albino
585006  1020695      Peter Brandon                 Minister
585007  1020695    David Spielberg            Jerry Bellamy
585008  1020695      Naomi Stevens            Woman Hostage
585009  1020695          Med Flory       Albino-Beating Cop
585010  1020695         Steve Shaw          Cop in Elevator
585011  1020695    Dino Washington          Cop in Elevator
585012  1020695   Anthony Eldridge                  Laugher
585013  1020695        Barry Russo       Man in Phone Booth
585014  1020695        Don Billett         Cop in Tee Shirt
585015  1020695         Hal Baylor           Police Captain
585016  1020695    Nancy Bonniwell      Girl in Airport Bar
585017  1020695    Don 'Red' Barry        Airport Bartender
585018  1020695         Karl Lukas                  Charley
585019  1020695  Gene Chronopoulos                Bartender
585020  1020695     Patrice Rohmer                    Linda
585021  1020695       Alvin Hammer       Liquor Store Clerk
585022  1020695       Dave Willock       Liquor Store Clerk
585023  1020695      Queenie Smith                 Customer
585024  1020695     Marilyn Stader                 Customer
585025  1020695     Robert Englund              Hold-up Man
585026  1020695     George Memmoli          Foot Fetish Man
585027  1020695       Fred Willard             Interrogator
585028  1020695          Thad Geer       Second Hold-up Man
585029  1020695       Kelly Wilder             Nancy Gaines
585030  1020695          Ben Young          First Detective
585031  1020695       Tasso Bravos             Boy on Beach
585032  1020695        Jim Hampton             Boy on Beach
585033  1020695     Nathan Harding             Boy on Beach
585034  1020695       John Furlong                   Waiter
585035  1020695     Jason Wingreen                 Jim Lang
585036  1020695          Ron Nyman             Pan Am Clerk
585037  1020695      Dante D'Andre                   Waiter
585038  1020695   Victoria Carroll                    Guest
585039  1020695       John Harding                 Attorney
585040  1020695          Bob Harks        Wounded Detective
585041  1020695        Dick Enberg  Radio Announcer (voice)

In [61]:
df_actors.query('name == "Natalie Portman"')

              id             name                                role
2409     1000035  Natalie Portman        Nina Sayers / The Swan Queen
2968     1000043  Natalie Portman                         Jane Foster
11712    1000188  Natalie Portman                       Padmé Amidala
12264    1000197  Natalie Portman       Jane Foster / The Mighty Thor
13726    1000223  Natalie Portman                       Padmé Amidala
...          ...              ...                                 ...
1935457  1123663  Natalie Portman  Pauline Friedman / Esther Friedman
2019620  1132227  Natalie Portman                             (voice)
2251809  1156644  Natalie Portman                                Self
2441727  1178241  Natalie Portman                              Ronnie
3021631  1253344  Natalie Portman                   Dominique Bellamy

[64 rows x 3 columns]

In [55]:
df_actors.query('role == "Policeman"')

              id               name       role
55       1000001      Carlos Jacott  Policeman
56       1000001           Adam Ray  Policeman
293      1000004  David Jean Thomas  Policeman
2350     1000033     Michael Graham  Policeman
2398     1000034     Burnell Tucker  Policeman
...          ...                ...        ...
5729186  1897519         Nick Nysum  Policeman
5735546  1901218      William Ellis  Policeman
5783422  1933408      Thomas Runkel  Policeman
5787660  1935528    Craig Colasanti  Policeman
5790504  1937032       Abe Ginsberg  Policeman

[3577 rows x 3 columns]