Import libraries

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import self

plt.style.use('ggplot')
pd.set_option('max_columns', 10)

Reading CSV and creation dataframe

In [19]:
df_actors = pd.read_csv('C:\\Users\\Windows11\\Desktop\\dataset\\actors.csv')

Checking CSV dimension

In [20]:
df_actors.shape

(5798450, 3)

Showing CSV line

In [21]:
df_actors.head(5)

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

Showing CSV index

In [26]:
df_actors.columns

Index(['id', 'name', 'role'], dtype='object')

Showing CSV columns types

In [27]:
df_actors.dtypes

id       int64
name    object
role    object
dtype: object

Obtaining a statistical summary of the numerical columns of the CSV DataFrame

In [28]:
df_actors.describe()

                 id
count  5.798450e+06
mean   1.302557e+06
std    2.551917e+05
min    1.000001e+06
25%    1.079557e+06
50%    1.236225e+06
75%    1.483358e+06
max    1.941597e+06

Show the first few rows of the dataframe

In [31]:
df_actors.head()

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie